import type { Metadata } from "next";
import "./globals.css";
import { Lora } from "next/font/google";
import { NavigationHeader } from "@/components/navigation-header";
import { ThemeProvider } from "@/components/theme-provider";

const lora = Lora({
	subsets: ["latin"],
	weight: ["400", "500", "700"],
	variable: "--font-lora",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body
				className={`${lora.variable} antialiased flex flex-col min-h-screen bg-white text-gray-900 dark:bg-neutral-900 dark:text-white transition-colors`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange
				>
					<NavigationHeader />
					<main id="content">{children}</main>
					<footer className="w-full max-w-2xl mx-auto px-4 sm:px-6 lg:px-8">
						<div className="py-6 border-t border-gray-200 dark:border-neutral-700">
							<div className="flex flex-wrap justify-between items-center gap-2">
								<div>
									<p className="text-xs text-gray-600 dark:text-neutral-400">
										© 2025 Marcelosmbr
									</p>
								</div>

								<ul className="flex flex-wrap items-center">
									<li className="inline-block">
										<span className="text-xs text-gray-600 dark:text-neutral-400">
											Next.js 15 + DatoCMS
										</span>
									</li>
								</ul>
							</div>
						</div>
					</footer>
				</ThemeProvider>
			</body>
		</html>
	);
}
